### ISSUE TITLE
User Error: Palette+ Clarification

### ISSUE THREAD

**Issue by cfelicio** [tomvandeneede/p2pp#106]
I noticed that while printing with P+ Accessory mode, the mosaic keychain never transitioned:

Expected:
![image](https://user-images.githubusercontent.com/7227683/114279055-86067f80-99e7-11eb-8d60-0a1b5fb31611.png)

Actual:
![image](https://user-images.githubusercontent.com/7227683/114279107-cd8d0b80-99e7-11eb-8487-b4e371423858.png)

Comparing the MSF from P2PP with Chroma, I noticed the PPM value was different. Turns out I used on my Gcode the following:

![image](https://user-images.githubusercontent.com/7227683/114279134-f31a1500-99e7-11eb-8dc5-c7eccd20db88.png)

;P2PP P+PPM=108925
;P2PP P+LOADINGOFFSET=29631

When in reality, I should be using the PPM obtained from Chroma:

![image](https://user-images.githubusercontent.com/7227683/114279158-0e852000-99e8-11eb-89d1-b4d2adfa81b5.png)

I made some changes to the doc to clarify this on the P+ section. Not sure how to check in, but leaving it here for reference in case other users make the same mistake, as its an easy one to overlook.
[P2PP user manual.docx](https://github.com/tomvandeneede/p2pp/files/6290410/P2PP.user.manual.docx)

**Comment by tomvandeneede** [comment]
thanks for the update, I will upload the changes into the manual

**Comment by cfelicio** [comment]
Awesome! Appreciate it!

**Comment by cfelicio** [comment]
Oh, just a quick note, noticed the code on the document still shows:

;P2PP ACCESSORYMODE_MAF
;P2PP P+PPM=<ppm value>
‘P2PP P+LOADINGOFFSET=<loading offset>


I think for the P+, correct is (fix the ' for ;, and MAF for MSF):

;P2PP ACCESSORYMODE_MSF
;P2PP P+PPM=<ppm value>
;P2PP P+LOADINGOFFSET=<loading offset>

Cheers,
Carlos
