### ISSUE TITLE
Printer Profile ID

### ISSUE THREAD

**Issue by dbsweeny** [tomvandeneede/p2pp#11]
Under "Mandatory Steps" of the "Configuration of Slic3rPE" section, the user is instructed to find and save their printer profile ID number to "have it ready for the next steps", but then it's never mentioned again in the rest of the process. Please explain what the user is supposed to do with this number.

**Comment by weevilgenius** [comment]
You add it to the first line of the Start GCode (step 4 of Printer settings):

```
;P2PP PRINTERPROFILE=REPLACE_WITH_YOUR_PRINTER_PROFILE_OBTAINED_FROM_ABOVE
```

**Comment by dbsweeny** [comment]
My thanks!

**Comment by tomvandeneede** [comment]
Changed wording to match exact terms and avoid confurion
