### ISSUE TITLE
Addition for Reference-Configurations wiki

### ISSUE THREAD

**Issue by apopticon** [tomvandeneede/p2pp#111]
<pre>
Prusa 
i3 MK3S
Direct
bed_shape = 0x0,250x0,250x210,0x210

Link to tube holder: https://www.thingiverse.com/thing:4807526

/* START G-CODE */
; many tweaks based on info found at https://projects.ttlexceeded.com
; Marc Siegel (apopticon)
; PrusaSlicer start gcode for Prusa i3 Mk3
; Last updated 20210316
M300 S60 P10 ; chirp
M117 Initializing
; Set coordinate modes
G90 ; use absolute coordinates
M83 ; extruder relative mode
; Reset speed and extrusion rates
M200 D0 ; disable volumetric e
M220 S100 ; reset speed
M221 S100 ; reset extrusion rate
; Set initial warmup temps
M117 Nozzle preheat
M104 S160 ; set extruder no-ooze temp
M140 S{if printer_model=~/.*MK3S.*/}[first_layer_bed_temperature]{else}{max(first_layer_bed_temperature[0],80)}{endif}  ; set bed PINDA warmup temp
; Nozzle warmup before home to avoid driving hardened ooze into PEI surface
M109 S160 ; wait for extruder no-ooze warmup temp before mesh bed leveling, cool hot PINDA
; Home
M300 S40 P10 ; chirp
M117 Homing
G28 W ; home all without mesh bed level
; Present bed for final cleaning
G0 Z3; Raise nozzle before move
G0 X125 Y180 F10200; Move nozzle to PINDA warming position
G0 Z0.15 F10200; Lower nozzle to PINDA warming position
; Wait for PINDA warmup
M117 PINDA warmup
{if printer_model=~/.*MK3S.*/}
M117 Mk3S detected, no warmup required
{else}
M117 Mk3 Waiting for PINDA warmup
M860 S35 ; wait for PINDA temp to stabilize
{endif}
M140 S[first_layer_bed_temperature] ; set target bed temp
G0 Z3; Raise nozzle before move
; Mesh bed leveling
M300 S40 P10 ; chirp
M117 Mesh bed leveling
G80 ; mesh bed leveling
M117 Saving results
G81 ; save mesh leveling results
; Final warmup routine
M117 Final warmup
G0 Z5; Raise nozzle to avoid denting bed while nozzle heats
M140 S[first_layer_bed_temperature] ; set bed final temp
M104 S[first_layer_temperature] ; set extruder final temp
M109 S[first_layer_temperature] ; wait for extruder final temp
M190 S[first_layer_bed_temperature] ; wait for bed final temp
; Prime line routine
M300 S40 P10 ; chirp
M117 Printing prime line
G0 Z0.15 ; Restore nozzle position - (thanks tim.m30)
M900 K0; Disable Linear Advance for prime line
G92 E0.0 ; reset extrusion distance
G1 Y-3.0 F1000.0 ; go outside print area
G1 E2 F1000 ; de-retract and push ooze
G1 X20.0 E6  F1000.0 ; fat 20mm intro line @ 0.30
G1 X60.0 E3.2  F1000.0 ; thin +40mm intro line @ 0.08
G1 X100.0 E6  F1000.0 ; fat +40mm intro line @ 0.15
G1 E-0.8 F3000; retract to avoid stringing
G1 X99.5 E0 F1000.0 ; -0.5mm wipe action to avoid string
G1 X110.0 E0 F1000.0 ; +10mm intro line @ 0.00
G1 E0.6 F1500; de-retract
G92 E0.0 ; reset extrusion distance
; Final print adjustments
M300 S40 P10 ; chirp
M117 Preparing to print
; Adjust extrusion rate if desired
; M221 S{if layer_height >= 0.32}90{else}100{endif} ; compensate for thick layer heights
M117 Print in progress

;P2PP PRINTERPROFILE=cbf6d35506c9d38e
;P2PP SPLICEOFFSET=35
;P2PP MINSTARTSPLICE=100
;P2PP MINSPLICE=80
;P2PP MATERIAL_DEFAULT_1_0_1
;P2PP MATERIAL_PVA_PVA_0_0_0
;P2PP MATERIAL_PVA_PLA_0_0_0
;P2PP MATERIAL_PLA_PLA_0_0_0
;P2PP MATERIAL_PET_PET_1_0_1

;P2PP PURGETOWERDELTA=10
;;P2PP PURGETOPSPEED=
;slow down on purge tower
;P2PP WIPEFEEDRATE=3000

;Optional - waits for user to close window after processing
;P2PP CONSOLEWAIT
    
; Following settings are optional (see description below)

;P2PP LINEARPINGLENGTH=350
;P2PP EXTRAENDFILAMENT=120

; Following optional settings control the SIDE TRANSITIONING (see description below)

;P2PP SIDEWIPELOC=X253.9
;P2PP SIDEWIPEMINY=45
;P2PP SIDEWIPEMAXY=195
;P2PP SIDEWIPECORRECTION=1.0
;P2PP BEFORESIDEWIPEGCODE ;--ENTER GCODE TO BE EXECUTED BEFORE SIDEWIPE (one coomand per line,can be multiple lines)
;P2PP AFTERSIDEWIPEGCODE ;--- ENTER GCODE TO BE EXECUTED AFTER SIDEWIPE (one coomand per line,can be multiple lines)

;try to auto adjust for short splices
;;P2PP AUTOADDPURGE

;P2PP DO_NOT_GENERATE_M0
;That's all folks!
;P2PP CONFIGEND

;* END P2PP version

**************************************************************************************************************
/* END G-CODE */
G4 ; wait
M221 S100
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 F1000.0 ; set feed rate
G1 E-3 ; retract
{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+30, max_print_height)}{endif} ; Move print head up
G1 X20 Y200; home X axis

M84 ; disable motors
M117 Print Complete
</pre>

**Comment by tomvandeneede** [comment]
Hi MArk,

just verified the main config topics (it is the idea to provide a config for basic processing only at this point. 
I left all parameters to default (no fullpruge, tower delta, sidewise etc)…. 

I added the link to the tube holder though, that is definitely useful stuff.

Thanks for your reaction/

Regards

Tom Van den eede

**Comment by tomvandeneede** [comment]
Updated the material in the MK3S section with the appropriate parts of P2PP config
