### ISSUE TITLE
Purge tower got speed up drastically when processed

### ISSUE THREAD

**Issue by Siwat2545** [tomvandeneede/p2pp#119]
The speed of the purge tower increases drastically and also have some inconsistent speed
Before Process:
![image](https://user-images.githubusercontent.com/8684409/152330469-d035ade5-49ef-455a-8e14-b519909bc0c0.png)
After Process:
![image](https://user-images.githubusercontent.com/8684409/152330579-e18d8239-5699-4812-9372-828249825e94.png)

Project file, process, unprocessed gcode file attached
[bugreport.zip](https://github.com/tomvandeneede/p2pp/files/7993929/bugreport.zip)

slicer used: https://github.com/supermerill/SuperSlicer

**Comment by tomvandeneede** [comment]
Will look into this

**Comment by tomvandeneede** [comment]
Hi I think I found what is causing but neet some further testing before compiling ut a new version of the tool.   Hope to get around this during the weekend.

**Comment by tomvandeneede** [comment]
Can you please check with 8.0.17 as it seems to process fine on my latest version
![image](https://user-images.githubusercontent.com/45884325/152636130-7b5ffbec-43ac-439f-a2da-381760dd592e.png)
There was an issue in your gcode for sure with the high speed, but when processing with the latest 8.0.17 version the speeds seem to be what is about to be expected.

**Comment by Siwat2545** [comment]
The newest version does indeed fix the issue, thank you.
This also raise another issue, your update checking seems to not be working. (:
