### ISSUE TITLE
First purge line before Z un-hop

### ISSUE THREAD

**Issue by superblobmonster** [tomvandeneede/p2pp#127]
It appears as though in the purge tower, the first line in the purge tower is happening before the tool head moves back down into the plane for printing.

Accessory mode, klipper tool changes, P3P

![image](https://user-images.githubusercontent.com/7859989/162503090-bc0faaf3-fafa-4a28-b0b2-338cd6c3831e.png)
![image](https://user-images.githubusercontent.com/7859989/162503101-b790812a-071d-441a-a046-4132e9429224.png)

Accessory mode, klipper machine, P3P

[3C_Lizard.zip](https://github.com/tomvandeneede/p2pp/files/8454533/3C_Lizard.zip)

**Comment by tomvandeneede** [comment]
Should be solved in 8.0.34
