### ISSUE TITLE
Exporting to TMP folder

### ISSUE THREAD

**Issue by superblobmonster** [tomvandeneede/p2pp#128]
Exporting unprocessed gcode puts the file in: /tmp/.[group of numbers].gcode_unprocessed.pp

Only occurs with SuperSlicer 2.4+ does not happen in 2.3. Assuming same is true for Prusaslicer. Still not sure if this is an issue with P2PP or something that changed with Prusaslicer.

Linux Mint 20.1 Cinnamon 5.13.0-39-generic
Running SuperSlicer-ubuntu_18.04-2.4.58.2.AppImage
P2PP v33 compiled from source
![image](https://user-images.githubusercontent.com/7859989/162507835-ce476669-1a02-47ed-a9e5-3d4426260d57.png)

**Comment by tomvandeneede** [comment]
this is a change in PS/Superslicer shwere they store the temporary files.   I have chosen to store the copy with the unprocessed file in the same spot for the very same reason Slicer changed their behaviour.   The final target may be on an SD card and the interfacing may be slow + disk size mey be insufficient... The location of the file is indicated in P2PP and as this is for debugging purposed mainly there is I think no need to change the behaviour
