### ISSUE TITLE
Making p2pp.sh executable

### ISSUE THREAD

**Issue by dbsweeny** [tomvandeneede/p2pp#14]
I'm having difficulty making the p2pp.sh file exectuable. I've completed all steps, but I don't get the appropriate error message. Instead I get a Python Launcher warning (attached). Must I be using Python 2.7 or 3.0 as per the instructions, or might 3.7, which I'm using, work also? 

![Screen Shot 2019-03-13 at 4 43 02 PM](https://user-images.githubusercontent.com/43355368/54313276-58a03b00-45af-11e9-91be-ab3272df6025.png)

**Comment by skellatore** [comment]
Hi dbsweeny - This should be OK - the error message is a bit different to normal in MacOSX. It's complaining that you have not provided an input file (which is automatically sent when using Slic3r). If you were to execute the script again with say....    ./p2pp.sh somegcodefile.gcode      it will work. you sholuld be OK to proceed to setting up and using Slic3r now.
