### ISSUE TITLE
purge tower first layer height 0,7mm

### ISSUE THREAD

**Issue by JamesBond0815** [tomvandeneede/p2pp#157]
When printing with P2PP Purgetowerdelta, the first layer is printed at 0.7mm in air.
PrusaSLicer 2.6.0-alpha5 / P2PP 9.00.01 / Caribou MK3S 220 / Palette 3Pro

[201901MosaicKeychain1_0.2mm_GelbPLAREDLINE_Caribou_MK3S_220_42m.mcfx.zip](https://github.com/tomvandeneede/p2pp/files/11069301/201901MosaicKeychain1_0.2mm_GelbPLAREDLINE_Caribou_MK3S_220_42m.mcfx.zip)
[8992.zip](https://github.com/to
![IMG_5994](https://user-images.githubusercontent.com/127897226/227727710-e23d0b00-fac6-4169-ae46-1cdc05797b96.jpg)
mvandeneede/p2pp/files/11069302/8992.zip)
[Caribou 220 Gelb.zip](https://github.com/tomvandeneede/p2pp/files/11069316/Caribou.220.Gelb.zip)

**Comment by tomvandeneede** [comment]
which version of p2pp are you using?Op 25 mrt. 2023 om 16:53 heeft JamesBond0815 ***@***.***> het volgende geschreven:﻿
When printing with P2PP Purgetowerdelta, the first layer is printed at 0.7mm in air.
PrusaSLicer 2.6.0-alpha5 / P2PP 9.00.01 / Caribou MK3S 220 / Palette 3Pro
201901MosaicKeychain1_0.2mm_GelbPLAREDLINE_Caribou_MK3S_220_42m.mcfx.zip
[8992.zip](https://github.com/to

mvandeneede/p2pp/files/11069302/8992.zip)
Caribou 220 Gelb.zip

**Comment by tomvandeneede** [comment]
Can you send me the unprocessed gcode please so I can try to figure out what goes wrong.

**Comment by JamesBond0815** [comment]
[8992.zip](https://github.com/tomvandeneede/p2pp/files/11071230/8992.zip)
P2PP Version: 9.00.01
PrusaSlicer: 2.6.0 Apha 5
Caribou MKS3S 220

**Comment by JamesBond0815** [comment]
P2PP Version: 9.00.01
PrusaSlicer: 2.6.0 Apha 5
Caribou MKS3S 220

 

Von: Tom Van den Eede ***@***.***> 
Gesendet: Sonntag, 26. März 2023 09:58
An: tomvandeneede/p2pp ***@***.***>
Cc: JamesBond0815 ***@***.***>; Author ***@***.***>
Betreff: Re: [tomvandeneede/p2pp] purge tower first layer height 0,7mm (Issue #157)

 

Can you send me the unprocessed gcode please so I can try to figure out what goes wrong.

**Comment by tomvandeneede** [comment]
closed after no feedback received ... assuming issue solved
