### ISSUE TITLE
Error with single color prints

### ISSUE THREAD

**Issue by Killerskyman** [tomvandeneede/p2pp#165]
prusaslicer version: 2.6.0
p2pp version: 9.00.03
palette: palette 3 pro

When trying to print with palette with a single color the palette errors with error code '149'.

This is mainly in reference to #149 where i had the same issue and caused me quite a headache with a 12 hour print when it failed in the last 20 minutes. 

Having the same workflow and being able to configure the 'backup drives' for single color prints would be good and at minimum p2pp should at least give an error code beforehand that single color prints are not supported.

**Comment by Killerskyman** [comment]
so it's actually like a firmware/software issue with the p3 itself then? wack.

**Comment by tomvandeneede** [comment]
Iamaffraid so but maybe mosaic can solve in a next releaseOp 26 jun. 2023 om 19:23 heeft Skyler Cleland ***@***.***> het volgende geschreven:﻿
so it's actually like a firmware/software issue with the p3 itself then? wack.

**Comment by Killerskyman** [comment]
cool thanks for replying.
