### ISSUE TITLE
Missing documentation for `FIRMWARE_PURGE_LENGTH`

### ISSUE THREAD

**Issue by cyberhuman** [tomvandeneede/p2pp#189]
The colors in my first print with P2PP came out a bit skewed because there is a firmware purge and the parameter `FIRMWARE_PURGE_LENGTH` wasn't documented. It would be nice to at least mention it in the documentation.
The setting was deemed important enough by the Mosaic team to be added in their Canvas slicer:
![image](https://github.com/tomvandeneede/p2pp/assets/979624/1fb8acb2-17ec-4e3b-b4b3-cb1a101baeea)

Thank you for this project!

**Comment by tomvandeneede** [comment]
For which printer is this used?   Is it just an amount of material added to the first splice before the printing starts?  Just would like to understand how to implement

**Comment by cyberhuman** [comment]
I tested it and it works. I can also confirm the extrusion and splice lengths are calculated correctly because I had an unrelated issue and checked everything thoroughly.

**Comment by tomvandeneede** [comment]
will add it next time I make an update
