### ISSUE TITLE
Beta version wont run with Python 3.7

### ISSUE THREAD

**Issue by ramble392** [tomvandeneede/p2pp#29]
Trying to run the beta edition of P2PP gets a number of syntax errors with Python 3.7, mostly on the import statements where the import file looks like it needs a folder qualifier. For example, in logfile.py, the 

**import gui**
 I changed to 
**import p2pp.gui as gui**

There's also a couple of places where a function is called without parentheses around the arguments:

In version.py:
**printf "failed to load..."**
I changed to
**printf("failed to load...")**

I'm not all that familiar with Python, so It may be I'm missing an environment configuration setting or something like that.

**Comment by tomvandeneede** [comment]
thanks for reporting, forgot to test on 3.7 yesterday my wrong
