### ISSUE TITLE
Text output on palette2's screen

### ISSUE THREAD

**Issue by mylife4aiurr** [tomvandeneede/p2pp#3]
I know you are working on this just making an official issue. 

Would love to see usable text instructions on palettes screen, instructing user during loading of filament in addition to the color filament depicted on screen.

**Comment by tomvandeneede** [comment]
Will be available in next release of the script.   Meanwhile a workaround can be to duplicate the filament entries in Slic3r and add the color to the name.  

Having one profile per roll of filament in your collection has the advantage that you have the width calibration for each individual filament on record so better results...downside is that a change might have to be repeated many times if you want to change a parameter.  Would be nice to have parent filament in slic3r with main settings and derived  ones where you can alter individual settings, but that's a slicer thing.
