### ISSUE TITLE
Dev version removed custom tool change code, along with temp M106

### ISSUE THREAD

**Issue by chernogorsky** [tomvandeneede/p2pp#32]
If you try working with different temp filament, it does not work properly

it has
;--- P2PP removed [Tool Unload]M104 S210 
instead of 
M104 S210

**Comment by tomvandeneede** [comment]
This is being worked on

Have found some other issues with the side wipe

 

Rewrite is taking a little longer than expected

**Comment by chernogorsky** [comment]
That one with a regular purge tower, not a side. 
PrusaSlicer 2.1.0.rc+20190904

**Comment by chernogorsky** [comment]
[support_test_low.3mf.txt](https://github.com/tomvandeneede/p2pp/files/3587957/support_test_low.3mf.txt)

**Comment by tomvandeneede** [comment]
yep I understand
but currently there is also an issue with sidewise I am fixing, this is why I cannot immediately fix your issue, but it will be part of the current fix

**Comment by tomvandeneede** [comment]
I uploaded 3.4.0 that I expect should solve this issue.
Still beta but worth the try

**Comment by tomvandeneede** [comment]
Latest version does no longer remove any commands related to temperature
