### ISSUE TITLE
Too many short splice warrnings

### ISSUE THREAD

**Issue by chernogorsky** [tomvandeneede/p2pp#33]
After upgrade to 3.4 received plenty of splice warnings
have tried increase brim length, multiple objects, purge tower

[without_p2pp.gcode.txt](https://github.com/tomvandeneede/p2pp/files/3606085/without_p2pp.gcode.txt)
[p2pp.3mf.txt](https://github.com/tomvandeneede/p2pp/files/3606086/p2pp.3mf.txt)
[with_pp2p.gcode.txt](https://github.com/tomvandeneede/p2pp/files/3606087/with_pp2p.gcode.txt)

# general version info
MajorVersion = 3
MinorVersion = 4
Build = 0

**Comment by tomvandeneede** [comment]
soved by adding extra requirement that Z-Hop cannot be ZERO
