### ISSUE TITLE
Win 10 / PS 2.1 / p2pp dev (16.09.2019)

### ISSUE THREAD

**Issue by geka79** [tomvandeneede/p2pp#34]
I get the following error message after the graphic progress window:

Traceback (most recent call last):
  File "C:\......\p2pp-dev\\p2pp.py", line 145, in <module>
    main(vars(arguments.parse_args()))
  File "C:\.......\p2pp-dev\\p2pp.py", line 91, in main
    args['silent']
  File "C:\.......\p2pp-dev\p2pp\mcf.py", line 587, in generate
    parse_gcode()
  File "C:\.......\p2pp-dev\p2pp\mcf.py", line 290, in parse_gcode
    if v.parsedgcode[-1].get_parameter("E", 0) < 0:
TypeError: '<' not supported between instances of 'str' and 'int'
Drücken Sie eine beliebige Taste . . .

**Comment by tomvandeneede** [comment]
could you please send me the gode file you tried to process?

**Comment by geka79** [comment]
No Problem. I will send it in the evening.

Gesendet mit der GMX iPhone App

Am 17.09.19 um 07:19 schrieb tomvandeneede

**Comment by geka79** [comment]
Gesendet: Dienstag, 17. September 2019 um 07:19 Uhr
Von: "tomvandeneede" <notifications@github.com>
An: tomvandeneede/p2pp <p2pp@noreply.github.com>
Cc: geka79 <gerhard.kals@gmx.at>, Author <author@noreply.github.com>
Betreff: Re: [tomvandeneede/p2pp] Win 10 / PS 2.1 / p2pp dev (16.09.2019) (#34)


could you please send me the gode file you tried to process?

**Comment by tomvandeneede** [comment]
issue was with M84 command with explicit callout of stepper axis info.
pasring has been updated to prevent this from happening
