### ISSUE TITLE
Homing Z throws an error

### ISSUE THREAD

**Issue by mmontminy** [tomvandeneede/p2pp#38]
With the current dev branch (3.5.16) if you have a G28 Z in your gcode, you get the following stack trace:

> Traceback (most recent call last):
>   File "C:\p2pp\\p2pp.py", line 145, in <module>
>     main(vars(arguments.parse_args()))
>   File "C:\p2pp\\p2pp.py", line 91, in main
>     args['silent']
>   File "C:\p2pp\p2pp\mcf.py", line 733, in generate
>     parse_gcode()
>   File "C:\p2pp\p2pp\mcf.py", line 332, in parse_gcode
>     delta = (to_z - cur_z)
> TypeError: unsupported operand type(s) for -: 'str' and 'int'

**Comment by tomvandeneede** [comment]
Should be solved in 3.5.17
thanks for bringing this up
