### ISSUE TITLE
make extra filament at the end of print

### ISSUE THREAD

**Issue by mylife4aiurr** [tomvandeneede/p2pp#4]
For direct drive printers this is not so important. 

But for bowden style printers like a delta or CR10 - Palette2 needs to produce extra filament at end of print so users can pull filament out from bowden tube.

**Comment by tomvandeneede** [comment]
Will be a parameter in next release

**Comment by ricarant** [comment]
Hi any news for the bowden setup, i did try p2pp but i got short of filament as well i have a cr10s

**Comment by skellatore** [comment]
Resolved
