### ISSUE TITLE
Fails to increase Z back to print height when using PURGETOWERDELTA

### ISSUE THREAD

**Issue by mjgorman** [tomvandeneede/p2pp#50]
After the first purge to the tower (after the initial layer) the print several layers in the printer fails to go back up to the Z height it was at before lowering to the tower for purge, causing it to move back and bash into the model (or supports in my case) and start printing again at this lower height. 

PrusaSlicer 2.1.0 Linux
P2PP latest Dev Branch

Unprocessed Gcode:
https://drive.google.com/file/d/11UOdeYK5N3cAy_aR6CEcezzTv7hB-Jug/view?usp=sharing

Processed Gcode:
https://drive.google.com/file/d/1FgJZJjdj_vUA0tg-EbYNF3FCX1NZStlu/view?usp=sharing

**Comment by tomvandeneede** [comment]
Michal, 

Could you specify at which layer this happens approx.
I see all the tower moves prefixed and suffixed with Z- moves as should

**Comment by tomvandeneede** [comment]
added check for required Z-hop on retracts
