### ISSUE TITLE
Side purge speed way too fast

### ISSUE THREAD

**Issue by jessegrunert** [tomvandeneede/p2pp#57]
I just recently got my printer set up for side transitions. When I set it up, everything worked fine, the head moved to the right position, however the feed rate was crazy high. Basically causing my extruder to instantly skip and very little filament was actually extruded. I had set a narrow y-min/y-max (200/300) as I didn't want the y axis to move around too much.

Is there a value or setting that I'm missing to control this?

**Comment by tomvandeneede** [comment]
there are 2 commands
WIPEFEEDRATE=xxxx sets the wipe federate in mm/min (movement)

**Comment by jessegrunert** [comment]
Thanks, I didn't realize this would relate to the sidewipe as well. Confirmed that it works as expected. Thanks again for writing such an awesome piece of code!
