### ISSUE TITLE
text of colors cut off palette2 screen

### ISSUE THREAD

**Issue by mylife4aiurr** [tomvandeneede/p2pp#6]
p2pp rc1
red ok. only 3 letters.
Black and White cut off
![20190121_093640](https://user-images.githubusercontent.com/31583073/51481507-063a5f00-1d62-11e9-9cb6-08d6a0e3f6bf.jpg)
![20190121_093636](https://user-images.githubusercontent.com/31583073/51481510-076b8c00-1d62-11e9-95f1-fec7464c137c.jpg)
![20190121_093646](https://user-images.githubusercontent.com/31583073/51481514-09354f80-1d62-11e9-9956-9be72387f41a.jpg)

**Comment by tomvandeneede** [comment]
solved with version 2.0
