### ISSUE TITLE
MFC

### ISSUE THREAD

**Issue by Kelvinator78** [tomvandeneede/p2pp#61]
Although I add the .mfc.gcode for the file extensions and sliced it to my SD card to put in the Palette 2, it wouldn't see what I did as the file format is gcode and not mfc

**Comment by tomvandeneede** [comment]
Hi,

Can you please be a little bit more specific on what you are trying to achieve.
*/ mcf feels are still gcode files, they are just extended with additional data…please PM me the file and I  will take a look
*/ can you confirm p2pp has worked (popup screen)

**Comment by Kelvinator78** [comment]
Now it says WARNING: No Algorithm defined for transitioning ABS to ABS.
Using Default.

Also on the manual under Palette+ setup when I have a Palette 2 Pro it says
that it will generate a Gcode file as well as a MSF file and there is a
script code for it but don't know where to copy and paste it.

Kelvin Case

**Comment by tomvandeneede** [comment]
ok so you are now going from ABS to ABS in your print.   If you do so you need to make sure to specify for the Palette how to splice ABS to ABS
 
you will need to add a line 

;P2PP MATERIAL_ABS_ABS_[Heating]_[Compression]_[reverse] 
to your print with the desired parameters.

**Comment by Kelvinator78** [comment]
On the manual under Palette+ setup when I have a Palette 2 Pro it says that
it will generate a Gcode file as well as a MSF file and there is a script
code for it but don't know where to copy and paste it.

**Comment by tomvandeneede** [comment]
All config goes into the startup gcode

Please use the facebook support group for your follow up questions as I am not able to always monitor this account

regards

**Comment by tomvandeneede** [comment]
Looks like a setup issue, please use the facebook group to further discuss

**Comment by Kelvinator78** [comment]
I have figured it out. In the website manual it says you have to save it as
filename.mfc.gcode which I was doing. I now have saved it as filename.maf
and that worked

**Comment by tomvandeneede** [comment]
You should not have to specify filenames.   The programme should create 2 files by itself one gcode for the printer and one msf/maf file for the P2 memory card
this is assuming that you want to print in accessory mode.   The problem specification has been rather vague.

Please use facebook for support.
