### ISSUE TITLE
Accerssory mode status

### ISSUE THREAD

**Issue by maziggy** [tomvandeneede/p2pp#75]
I'm wondering what the current status of accessory mode is. Is it still experimental?

Thanks, Martin

**Comment by tomvandeneede** [comment]
Hi,

still in alpha,

I don’t have the bandwidth to test 
I really depend on user feedback for testing on this one and nearly nobody is using this mode.

it generates proper files but that is as far as I can test

would need one or two actual prints to confirm all is good

**Comment by maziggy** [comment]
I just started printing the buffer parts. Will come back to you in a few days and provide you the results.

**Comment by tomvandeneede** [comment]
pending no further followup
