### ISSUE TITLE
Removal of semicolons breaks thumbnail functionality.

### ISSUE THREAD

**Issue by Caelarius** [tomvandeneede/p2pp#77]
Prusaslicer has the option to generate thumbnails of the object in the gcode. These thumbnails are stored as asciitext within the gcode and are picked up by Octoprint to show the thumbnail. Because p2pp seems to remove some semicolons surrounding these thumbnails, they end up getting ignored by Octoprint.

I've made a simple example of two test cubes to illustrate:

Attachment 1 (MK3_Pretty PLA V4.1.5.ini (LA 1.5) (Palette 2)_nozzle0.4_cubes.gcode) is the original file, generated by p2pp. Attachment 2 (MK3_Pretty PLA V4.1.5.ini (LA 1.5) (Palette 2)_nozzle0.4_cubes_fixed.gcode) is the fixed version with the semicolons as expected by Octoprint.

Files are available here: [https://www.dropbox.com/s/nkdk4sqpnp2rse5/p2pp%20thumbnails%20example.zip?dl=0](url)

**Comment by tomvandeneede** [comment]
Hi,

version 5.15 should fix this issue

regards
