### ISSUE TITLE
issues on new DMG version

### ISSUE THREAD

**Issue by wnc2** [tomvandeneede/p2pp#82]
app installs ok, but i have this error during script
![Schermata 2020-12-19 alle 10 12 23](https://user-images.githubusercontent.com/43959480/102685723-ee381800-41e2-11eb-8ae5-52bfabbca070.jpg)

**Comment by wnc2** [comment]
BTW the app generates a gcode after errors warning

**Comment by tomvandeneede** [comment]
correcting that

should be ready shortly

I started from 5.29 so there will be some things like this in there

regards

**Comment by tomvandeneede** [comment]
there is a lot of new stuff in there but this should be way more manageable than the previous methods with surplus you van setup multiple versions more easily

**Comment by tomvandeneede** [comment]
corrected in 5.29
