### ISSUE TITLE
Bed size wrong

### ISSUE THREAD

**Issue by PowerChaos** [tomvandeneede/p2pp#88]
Hi,
this is a other bug report

the bed size setting get ignored

this is my setting
```
;P2PP BEDORIGINX=0
;P2PP BEDORIGINY=-10
;P2PP BEDSIZEX=235
;P2PP BEDSIZEY=235
```
![image](https://user-images.githubusercontent.com/7650333/103461981-6b56a780-4d22-11eb-97a5-d395850d282e.png)

and this is the response ( with errors ofcourse )
```
P2PP Version: 6.02.08
Python Version: 3.9.1
Reading File C:\Users\Staff\AppData\Local\Temp\.PrusaSlicer.upload.ca19-ccba-61e7-49d1
Analyzing Prusa Slicer Configuration
All purge lenghts 70/70 OR 140. Purge lenghts may not have been set correctly.
SPLICE OFFSET: 30.00mm
Full purge reduction configured
Linear Ping interval of 350.00mm
Extra filament at end of print 550.00mm
Convert to absolute extrusion parameters
Analyzing Layers / Functional blocks
Manual bed size override, PrusaSlicer Bedshape configuration ignored.
Bed origin (15.0mm, 10.0mm)
Bed zise (190.0mm, 195.0mm)
`Analyzing tool loading scheme`
SIDEWIPE and SKIRTS are NOT compatible in PS2.2 or later
Side wipe activated
FULLURGEREDUCTION is incompatible with SIDEWIPE, parameter ignored
Generate processed GCode
Using sidewipe with undefined SIDEWIPELOC!!!
Generating GCODE file: C:\Users\Staff\AppData\Local\Temp\.PrusaSlicer.upload.ca19-ccba-61e7-49d1
```

**Comment by tomvandeneede** [comment]
yep it is taken from ps bed definition now  can you pls share your gcode

**Comment by tomvandeneede** [comment]
really need gcode files with all of these issues :-)   there are so many settings that trying to figure out what is causing the exact problem is difficult with the supplied info only

**Comment by PowerChaos** [comment]
[Logo-2_28m_20210102-175825.mcf.gcode.zip](https://github.com/tomvandeneede/p2pp/files/5760564/Logo-2_28m_20210102-175825.mcf.gcode.zip)

that is why i gave you my full profile :P  but here is the code

Greetings from PowerChaos

**Comment by tomvandeneede** [comment]
Hi 

Think I got it sorted


the full profile has issues that I clobber up my own config :-(   I have had numerous failed prints due to accidentally referring to a wrong profile
hence I prefer gcode reading


Bed processing should be automatic and I added an extra check and seems to be fine

Concerning the skirt, I have added a warning when skirt and fullpruge are used together for now.
hope to find a workaround soon, but forbittinf the skirt is likely the best option
You can always auto add purge to make up for short splices

**Comment by PowerChaos** [comment]
the skirt get used in my case for the first line, as it start extracting only after a few mm
normaly i use the build in "first line" but was not sure if it works with this plugin ( founded in docs that it should work ) 

thank you for your quick fixing 😄 
and for the gcode , next time i will add the gcode to my reply
for the bug i splitted this one up as it is not really related to the other bug

if i find more "bugs" i let you know

Thank you
Greetings from PowerChaos

**Comment by tomvandeneede** [comment]
thank you for reporting all this
really helps a lot ironing out issue

**Comment by PowerChaos** [comment]
update
the bed size error is gone
but now it just plain ignore the bed size settings
see Gcode and image :P

![image](https://user-images.githubusercontent.com/7650333/103464031-28500080-4d31-11eb-9a89-c8995b5fcf2d.png)
![IMG_1693](https://user-images.githubusercontent.com/7650333/103464051-4cabdd00-4d31-11eb-87ed-65937039aa5e.JPG)
[debug-Logo-2_28m_20210102-193100.mcf.gcode.zip](https://github.com/tomvandeneede/p2pp/files/5760703/debug-Logo-2_28m_20210102-193100.mcf.gcode.zip)

**Comment by tomvandeneede** [comment]
hmm let me see

**Comment by tomvandeneede** [comment]
intention is to obsolete bedside and take it from the printer definition.
what bed size does it report?

**Comment by PowerChaos** [comment]
this zip file will be my next test , changed the bed size offset and the report is a bit better ( unless it goes back to 0*0 then its just smaller xD ) 

it contians a few images to make things easyer
[p2pp.zip](https://github.com/tomvandeneede/p2pp/files/5760727/p2pp.zip)

i dit not test this print yet , but for the report answer
it report 220 * 220 and it extract 15 * 20
even when my settings was 0*-10
and in prusa my settings are 220*220 with -15 offset
but it just goes to the 0*0 value of my bed (even past the prime line ) 

i let my test run as i also use it for my color calibration 

Greets from PowerChaos

**Comment by tomvandeneede** [comment]
this is correct processing

5mm is added on the y-axis as this ie needed to cope with the introduction line printed by prusa.
there is no easy way to take this our on other printers.  Technically it should be harmless

**Comment by PowerChaos** [comment]
de nieuwe code heb ik geprobeerd
en zoals ik al had gedacht , de offset code werkt niet
die blijft op 0x0 staan ongeacht welke instelling je gebruikt
dit is de print van bovenste file
dit is het resultaat
![IMG_1696](https://user-images.githubusercontent.com/7650333/103464936-dfe81100-4d37-11eb-8a53-6b21ff8a6e07.JPG)
