### ISSUE TITLE
Implement after purge/tool change gcode for side wipe

### ISSUE THREAD

**Issue by tdiggity** [tomvandeneede/p2pp#9]
I've been playing with side wipe transitions, and they're great. One useful thing would be to add the ability to add gcode after purge/side wipe is done to help clear out any purge material that might have caught onto the nozzle and avoid dragging purged material over to the print.

**Comment by tomvandeneede** [comment]
cool idea.... need to figure out a way to do this 
👍

**Comment by tomvandeneede** [comment]
if you go into the dev branch, there is a description on how to add your own GCode before and after the side wipe block.  Let me know if this is sufficient

**Comment by tomvandeneede** [comment]
added to version 2.0
